### ISSUE TITLE
issues resolving DNSSEC queries with cloudflared as upstream

### ISSUE THREAD

**Issue by BreiteSeite** [pi-hole/FTL#1263]
### Versions
- Pi-hole: v5.7
- AdminLTE: v5.9 
- FTL:  v5.12.1

### Platform
- OS and version: Debian 11.2
- Platform:  Raspbery Pi 4, Docker Swarm + traefik

### Expected behavior
Can resolve careers.intuitive.com.

### Actual behavior / bug
Browser loads forever. dig reports error:

```
pi@rpi:~ $ dig @127.0.0.1 careers.intuitive.com
;; Truncated, retrying in TCP mode.
;; communications error to 127.0.0.1#53: end of file

;; communications error to 127.0.0.1#53: end of file
```

### Steps to reproduce

1. run `dig careers.intuitive.com` against your pihole

## Debug Token

- URL:  https://tricorder.pi-hole.net/rrUKKbsG/

### Additional context

I run pihole on a single-node docker swarm cluster. Bug happens when scaling to 1 replica as well.

Upstream DNS is a cloudflared container in version 2021.12.3.
DNSSEC on pi-hole is enabled.

#### Resolving the record directly via upstream (cloudflared) works fine

```
pi@rpi:~ $ dig @127.0.0.1 -p 5053 careers.intuitive.com

; <<>> DiG 9.16.22-Debian <<>> @127.0.0.1 -p 5053 careers.intuitive.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41953
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 5b87124b2c655d74fcaa48b961c9ebe59f15269145e14501 (good)
;; QUESTION SECTION:
;careers.intuitive.com.		IN	A

;; ANSWER SECTION:
careers.intuitive.com.	60	IN	CNAME	intuitive.phenompeople.com.
intuitive.phenompeople.com. 60	IN	CNAME	hubsite-prod13-62952224.us-east-1.elb.amazonaws.com.
hubsite-prod13-62952224.us-east-1.elb.amazonaws.com. 60	IN A 34.205.21.19
hubsite-prod13-62952224.us-east-1.elb.amazonaws.com. 60	IN A 35.173.207.80

;; Query time: 31 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Dec 27 17:37:57 CET 2021
;; MSG SIZE  rcvd: 364
```

#### Resolving other queries via pihole works fine
```
pi@rpi:~ $ dig @127.0.0.1 duck.com

; <<>> DiG 9.16.22-Debian <<>> @127.0.0.1 duck.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5310
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: bb98f8eaabbd5e4eacc8c68c61c9ee1560abe8faae3dede3 (good)
;; QUESTION SECTION:
;duck.com.			IN	A

;; ANSWER SECTION:
duck.com.		10	IN	A	52.142.124.215

;; Query time: 623 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Dec 27 17:47:17 CET 2021
;; MSG SIZE  rcvd: 89
```

#### Webinterface shows N/A Reply
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2171105/147491837-2db333eb-812f-443a-9ff2-9622a27211d3.png">

#### Long-Term query data for affected domain
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2171105/147491932-53259ed1-da75-4569-9d4a-e9fcf8be65c2.png">

#### Pi-Hole Remote output

<img width="901" alt="image" src="https://user-images.githubusercontent.com/2171105/147491702-d5a709c3-b0e7-4455-ba1e-e3f50875c490.png">

#### The domain is not on any blacklist or blocklist
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2171105/147491758-43eaa0ee-d3b5-4328-b49a-133443111a98.png">

#### tcpdump
Attached a tcpdump generated via `sudo tcpdump 'port 53 and (dst host localhost) or (src host 172.18.0.1)' -i docker_gwbridge -A -w bug.pcap`
~bug.pcap.zip~ (removed)

**Comment by DL6ER** [comment]
My analysis powers are severely limited right now but I just checked via remote SSH that this domain does indeed work from my Pi-hole with a local `unbound` instance as upstream resolver. I don't have cloudflare available myself.

Can you quote the corresponding lines from your log file `/var/log/pi-hole.log` please?

Screenshots I just generated from mobile:

![Screenshot_2021-12-27-17-57-20-98__01](https://user-images.githubusercontent.com/16748619/147492659-24c5f54a-b3c9-40fd-8745-0bff739f141f.jpg)


![Screenshot_2021-12-27-17-59-30-25__01](https://user-images.githubusercontent.com/16748619/147492596-cf2279ac-3e97-443a-bd11-2f608c60fa8d.jpg)

**Comment by BreiteSeite** [comment]
Thank you for that quick response.

I'm not sure if the upstream is responsible for this.

My /var/log/pihole.log:

```
Dec 27 18:23:40 dnsmasq[519]: query[A] careers.intuitive.com from 10.0.2.27
Dec 27 18:23:40 dnsmasq[519]: forwarded careers.intuitive.com to 172.17.0.1
Dec 27 18:23:40 dnsmasq[519]: dnssec-query[DNSKEY] phenompeople.com to 172.17.0.1
Dec 27 18:23:40 dnsmasq[519]: reply careers.intuitive.com is <CNAME>
Dec 27 18:23:40 dnsmasq[519]: reply intuitive.phenompeople.com is <CNAME>
Dec 27 18:23:40 dnsmasq[519]: reply hubsite-prod13-62952224.us-east-1.elb.amazonaws.com is 34.205.21.19
Dec 27 18:23:40 dnsmasq[519]: reply hubsite-prod13-62952224.us-east-1.elb.amazonaws.com is 35.173.207.80
Dec 27 18:23:40 dnsmasq[1888]: query[A] careers.intuitive.com from 10.0.2.27
```

**Comment by BreiteSeite** [comment]
If i change my upstream DNS to quad9, everything works but as soon as i change it back to my cloudflared resolver i trigger the bug. So it seems like a combination of dnsmasq/FTL and cloudflared.

Here is my swarm service config:

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    networks:
      - "traefik"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.dnstcp.entrypoints=dnstcp"
        - "traefik.tcp.routers.dnstcp.rule=HostSNI(`*`)"
        - "traefik.tcp.services.pihole.loadbalancer.server.port=53"

        - "traefik.udp.routers.dnsudp.entrypoints=dnsudp"
        - "traefik.udp.services.pihole.loadbalancer.server.port=53"
        
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
        - "traefik.http.services.pihole.loadbalancer.sticky.cookie=true"
        - "traefik.http.routers.pihole.rule=Host(`my-pihole-hostnamei`)"
        - "traefik.http.routers.pihole.service=pihole"
        - "traefik.http.routers.pihole.entrypoints=https"
        - "traefik.http.routers.pihole.tls=true"

  cloudflared:
    image: raspbernetes/cloudflared:latest
    command: "proxy-dns --address 0.0.0.0 --port 5053 --upstream https://dns11.quad9.net/dns-query"
    networks:
      - "traefik"
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.udp.routers.cloudflared.entrypoints=cloudflared"
        - "traefik.udp.services.cloudflared.loadbalancer.server.port=5053"
networks:
  traefik:
    external: true
    
volumes:
  etc-pihole:
  etc-dnsmasq:
````

**Comment by DL6ER** [comment]
Could you record a similar pcap for the case where it works fine? Should make it easier to precisely compare the answer returned by cloudflare and the other resolver and what the corresponding replies from FTL to dig are.

Also the pihole log snippets in both cases, please. 


Was there anything more with `dnsmasq[1888]` in the log above? This looks like a TCP retry. Just for completeness sake.

I'll have a look at your files/logs as soon as possible.

**Comment by BreiteSeite** [comment]
I tested it dnsmasq directly (to see if this might be an dnsmasq bug) on my raspberrypi (without swarm etc.) and couldn't reproduce. But a lot of variables changed here as well (networking etc) so i'm not sure how useful this is..

```
version: '3.3'
services:
  dnsmasq:
    image: 4km3/dnsmasq:2.86-r0-alpine-edge
    privileged: true
    network_mode: host
    command: "-d --log-queries --no-resolv --no-hosts -S 127.0.0.1#5059 -a 127.0.0.1 -p 5058 -y"
  cloudflared:
    image: raspbernetes/cloudflared:latest
    network_mode: host
    command: "proxy-dns --address 127.0.0.1 --port 5059 --upstream https://dns11.quad9.net/dns-query"

networks:
  pihole-test:
    ipam:
      driver: default
      config:
        - subnet: 172.68.0.0/16
```
