### ISSUE TITLE
Warning for long-term load is incorrect

### ISSUE THREAD

**Issue by Pingger** [pi-hole/FTL#1319]
### Versions

- Pi-hole:  5.9
- AdminLTE:  5.11
- FTL:  5.14

### Platform

- OS and version:  Ubuntu 20.04 Server Core

- Platform:  lxd

### Expected behavior

"Warnings" being
1. Correct
2. permanently hideable
3. Warnings not being shown without being logged in! 

### Actual behavior / bug

1. Getting 
```
"Long-term load (15min avg) larger than number of processors: 14.9 > 8
This may slow down DNS resolution and can cause bottlenecks."
```
Despite 
    - having 16 Processor-Cores on the Host and only a single one assigned to the container.
    - This Warning being completely irrelevant!
    - The warning annimation annoying the heck out of me.
2. Displaying the Wrong amount of processor cores
3. Warnings are visible

### Steps to reproduce

1. Install PI-Hole
2. Open the Admin UI

## Debug Token

- URL:   https://tricorder.pi-hole.net/efMfHbXk/

### Screenshots

![image](https://user-images.githubusercontent.com/4761298/159131690-b799c4ba-c1b1-4931-9360-3a987df11871.png)

### Additional context

I thought this would be fixed, but after >3 months this issue still persists.

**Comment by PromoFaux** [comment]
```
"Long-term load (15min avg) larger than number of processors: 14.9 > 8
```

> Despite
>  - having 16 Processor-Cores 

What CPU is in your machine?  Is it 16 actual cores, or 8 cores and 16 threads? This is pertinent information that would help in working out if this is indeed a bug or not

**Comment by Pingger** [comment]
It is a rented Server having an AMD EPYC™ 7702. And yes the contract actually contains 16Cores 16Threads. And htop correctly reports this:
![image](https://user-images.githubusercontent.com/4761298/159135182-a8ab7fec-29a9-454d-8a09-f78f094fee93.png)


The commented, that "this hadn'd been fixed" was aimed at the issue, that warnings are visible without login, which is just a plain a bad idea, since it would give a potential attacker the information, that and how many warnings were generated. I considered the issue so glaringly obvious, that I indeed did not report on it.

Regarding my attitude: Sorry, you unfortunately received the tail end of a discussion with the nextcloud support team and a previous experience with the pihole community.

**Comment by dschaper** [comment]
What does `lxc info --resources` show for the CPU limits?

**Comment by dschaper** [comment]
> It is a rented Server having an AMD EPYC™ 7702. And yes the contract actually contains 16Cores 16Threads. And htop correctly reports this:

Can you confirm this? It seems really odd that the vendor would do 16c/16t, that's a contradiction in itself. I'm pretty sure that they are providing you 8c/16t. HTOP shows threads, not cores. 

Can you show where you are seeing the actual warnings and not just the icon when you are not logged in?

**Comment by Pingger** [comment]
<details>
<summary>lxc info --resources</summary>


```
CPU (x86_64):
  Vendor: AuthenticAMD
  Name: AMD EPYC 7702P 64-Core Processor
  Caches:
    - Level 1 (type: Data): 64KiB
    - Level 1 (type: Instruction): 64KiB
    - Level 2 (type: Unified): 512KiB
    - Level 3 (type: Unified): 16MiB
  Cores:
    - Core 0
      Frequency: 0Mhz
      Threads:
        - 0 (id: 0, online: true, NUMA node: 0)
    - Core 1
      Frequency: 0Mhz
      Threads:
        - 0 (id: 1, online: true, NUMA node: 0)
    - Core 2
      Frequency: 0Mhz
      Threads:
        - 0 (id: 2, online: true, NUMA node: 0)
    - Core 3
      Frequency: 0Mhz
      Threads:
        - 0 (id: 3, online: true, NUMA node: 0)
    - Core 4
      Frequency: 0Mhz
      Threads:
        - 0 (id: 4, online: true, NUMA node: 0)
    - Core 5
      Frequency: 0Mhz
      Threads:
        - 0 (id: 5, online: true, NUMA node: 0)
    - Core 6
      Frequency: 0Mhz
      Threads:
        - 0 (id: 6, online: true, NUMA node: 0)
    - Core 7
      Frequency: 0Mhz
      Threads:
        - 0 (id: 7, online: true, NUMA node: 0)
    - Core 8
      Frequency: 0Mhz
      Threads:
        - 0 (id: 8, online: true, NUMA node: 0)
    - Core 9
      Frequency: 0Mhz
      Threads:
        - 0 (id: 9, online: true, NUMA node: 0)
    - Core 10
      Frequency: 0Mhz
      Threads:
        - 0 (id: 10, online: true, NUMA node: 0)
    - Core 11
      Frequency: 0Mhz
      Threads:
        - 0 (id: 11, online: true, NUMA node: 0)
    - Core 12
      Frequency: 0Mhz
      Threads:
        - 0 (id: 12, online: true, NUMA node: 0)
    - Core 13
      Frequency: 0Mhz
      Threads:
        - 0 (id: 13, online: true, NUMA node: 0)
    - Core 14
      Frequency: 0Mhz
      Threads:
        - 0 (id: 14, online: true, NUMA node: 0)
    - Core 15
      Frequency: 0Mhz
      Threads:
        - 0 (id: 15, online: true, NUMA node: 0)
```


</details>

<details>
<summary>lxc info --resources pihole</summary>


```
Name: pihole
Location: none
Remote: unix://
Architecture: x86_64
Created: 2022/02/12 18:31 UTC
Status: Running
Type: container
Profiles: default
Pid: 4818
Ips:
  eth0: inet    10.1.x.x      vethxxxxxxxb
  eth0: inet6   fe80::xxxx:xxxx:xxxx:xxxx        vethxxxxxxxb
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 28
  CPU usage:
    CPU usage (in seconds): 2679
  Memory usage:
    Memory (current): 433.61MB
    Memory (peak): 1.18GB
  Network usage:
    eth0:
      Bytes received: 179.39MB
      Bytes sent: 102.65MB
      Packets received: 592133
      Packets sent: 653153
    lo:
      Bytes received: 18.15MB
      Bytes sent: 18.15MB
      Packets received: 257322
      Packets sent: 257322
```

</details>

Yes, I can confirm, that the Core count is correct.



![image](https://user-images.githubusercontent.com/4761298/159135610-2babaf74-2eb7-4bc3-ae30-43ab4c0464a2.png)
Warning icon, with number of warnings
At no point did I say, that I can see the message content of the warnings without being logged in. But I can see how my initial Message could be interpreted as such.

> [...] , that and how many warnings were generated. [...]
