### ISSUE TITLE
Docker: Pihole-FTL->  DHCP server socket: Permission denied. 

### ISSUE THREAD

**Issue by idfxken** [pi-hole/FTL#1324]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate

**How familiar are you with the codebase?:**

5

---

**[BUG | ISSUE] Expected Behaviour:**
Docker - FTL starting

**[BUG | ISSUE] Actual Behaviour:**

Docker pihole-FTL keeps restarting

**[BUG | ISSUE] Steps to reproduce:**

Update to Debian 11.3 

**Log file output**

pihole-FTL.log inside the container : 

FATAL ERROR in dnsmasq core: failed to bind DHCP server socket: Permission denied

**Device specifics**

Hardware Type: X86_64
OS: Debian 11.3 with docker 20.10.14, build a224086
port 67-68 tcp/udp is not in use (checked with netstat -pan | grep 67)
Docker-compose has remained unchanged
```
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Brussels'
      WEB_PORT: 81
      ServerIP: 192.168.111.4
    volumes:
      - /srv/dockerconfigs/pihole/etc:/etc/pihole/
      - /srv/dockerconfigs/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: host
```
