### ISSUE TITLE
Import of local DNS records from v5 to v6 does not handle tab stops

### ISSUE THREAD

**Issue by oxivanisher** [pi-hole/FTL#2213]
### Versions

- Pi-hole:  v6.0.1
- AdminLTE:  v6.0
- FTL:  v6.0

### Platform

- OS and version:  Not important

- Platform:  Docker

### Expected behavior

I had manually created host entries in `/etc/pihole/custom.list` looking like this:
```plaintext
10.0.0.42	some.host.tld
10.0.0.23	another.host.tld
pi-hole/pi-hole#10.0.0.10	notinuse.host.tld

# Special hosts
10.0.0.11	whatever.host.tld # some comment
```
Pihole <v6 handled this without a problem, but the importer had its problem with the lines. Mainly it was splitting the lines not correctly because of the tab stop (\t) instead of space. I absolutely get it, that this will happen only once and after manual cleanup in the `/etc/pihole/pihole.toml` it works perfect. But ideally, the importer would handle the tabs like spaces.

### Actual behavior / bug

The webui had a list like:
```yaml
[
"10.0.0.42\tsome.host.tld","",
"10.0.0.23\tanother.host.tld","",
"#10.0.0.10\tnotinuse.host.tld","",
"# Special hosts","",
"10.0.0.11\twhatever.host.tld #  some comment",""
]

```

### Steps to reproduce

1. Create a `/etc/pihole/custom.list` on some v5
2. Upgrade to v6

## Debug Token

No

### Screenshots

No

### Additional context

I absolutely get it that this is not a priority problem or even don't needs to be fixed. But it might help someone else if this is at least documented here in the issues.

**Comment by DL6ER** [comment]
Thank you. Not everyone will have upgrade. Many may be waiting for us buffing out the rough edges and will only upgrade a few weeks later. That's in general a good idea as - even despite the very long and quite helpful beta testing - there will always be surprising configurations out there just like the one in your case. We simply failed to expect that this file has been edited manually using a different space separator.

However, looking at the code, I am confused how this might have happened. You really got the array looking like what you posted above?
```
[
"10.0.0.42\tsome.host.tld","",
"10.0.0.23\tanother.host.tld","",
"#10.0.0.10\tnotinuse.host.tld","",
"# Special hosts","",
"10.0.0.11\twhatever.host.tld #  some comment",""
]
```
I'm asking because we both have code that should suppress anything starting in `#` as well as suppressing empty entries. Still, even this strange configuration should just work. I did just verify that `\t` is no issue at all in the code.

**Comment by oxivanisher** [comment]
Yeah, I know that it probably is not really worth to spend too much time on it. :) And no worries, I found this pretty fast and fixing was easy since I still had the old files.

But it got me curious and I can reproduce it with this. This represents a anonymized but pretty "realistic" setup like I had it:

### `docker-compose.yml`
```yaml
---

version: "2"

services:
  pihole-lan:
    container_name: pihole-lan
    hostname: pihole-lan.supersecret.lan
    image: pihole/pihole:2024.07.0
    ports:
      - "8080:80/tcp"

    environment:
      TZ: 'Europe/Zurich'
      IPv6: 'true'
      WEBPASSWORD: 'somepassword'
      FTLCONF_RATE_LIMIT: 5000/60
    volumes:
      - 'pihole-lan-etc-volume:/etc/pihole/'
      - 'pihole-lan-dnsmasq-volume:/etc/dnsmasq.d/'
      - './custom-lan.list:/etc/pihole/custom.list'
    dns: []
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  pihole-lan-etc-volume:
    driver: local
  pihole-lan-dnsmasq-volume:
    driver: local

networks:
  default:
```

### `custom-lan.list`
```plaintext
10.42.20.1	firewall.supersecret.lan
10.42.20.4	hosta.supersecret.lan
10.42.20.7	hostab.supersecret.lan
10.42.20.30	hostc.supersecret.lan # a comment with a exclamation mark!
#10.42.20.30	hostd.supersecret.lan # the line is completely commented
10.42.20.48	hoste.supersecret.lan
#10.42.20.48	hostf.supersecret.lan # some comment

10.42.22.7	hostg.supersecret.lan
10.42.22.14	hosth.supersecret.lan

10.42.31.6	hosti.supersecret.lan
10.42.31.16	hostj.supersecret.lan
10.42.31.17	hostk.supersecret.lan

# temp for some project (oxivanisher, 20242424)
10.42.31.40	hostl.supersecret.lan

```

Then `docker compose up`, shut it down and change the tag to `2025.02.0` or `2025.02.2` (tested both) and again `docker compose up`. Now the gui looks like this:
![Image](https://github.com/user-attachments/assets/9fac5e5b-66ab-4dc2-ae8e-46c978547255)

And in the container:
```bash
$ docker exec -it pihole-lan bash
pihole-lan:/# grep "Array of custom DNS records each one in HOSTS form" /etc/pihole/pihole.toml  -A13
  #     Array of custom DNS records each one in HOSTS form: "IP HOSTNAME"
  hosts = [
    "10.42.20.1\tfirewall.supersecret.lan",
    "10.42.20.4\thosta.supersecret.lan",
    "10.42.20.7\thostab.supersecret.lan",
    "10.42.20.30\thostc.supersecret.lan # a comment with a exclamation mark!",
    "10.42.20.48\thoste.supersecret.lan",
    "10.42.22.7\thostg.supersecret.lan",
    "10.42.22.14\thosth.supersecret.lan",
    "10.42.31.6\thosti.supersecret.lan",
    "10.42.31.16\thostj.supersecret.lan",
    "10.42.31.17\thostk.supersecret.lan",
    "10.42.31.40\thostl.supersecret.lan"
  ] ### CHANGED, default = []
```

Then I tried to add a new entry in the gui to check how the `.toml` will look and it doesn't like it :D
![Image](https://github.com/user-attachments/assets/c98cd22d-e8ca-4a7d-8385-c5e0dad9a473)

Checking my "fixed" configuration, it should just be a list of strings, each containing the ip, a space and then the hostname.
