### ISSUE TITLE
FTL Crashes if FTLCONF_webserver_api_password has a value set

### ISSUE THREAD

**Issue by uurf** [pi-hole/FTL#2242]
### Versions

- Core version is v6.0.3 (Latest: v6.0.3)
- Web version is v6.0.1 (Latest: v6.0.1)
- FTL version is v6.0.1 (Latest: v6.0.1)

### Platform

- OS and version:  

- Platform:  Device: Synology DS1817+
DSM 7.2.2-72806 Update 3
Docker Compose via Synology Container Manager 20.10.23-1437

### Expected behavior

Having set a password using  `FTLCONF_webserver_api_password: '<password>'` I expect the web service to load on `https://<adress>:8181/admin` and to be challenged for the password I set.

### Actual behavior / bug

FTL Crashes.

### Steps to reproduce

1. build a docker container using this compose code:

```
name: pihole6
services:
    pihole:
        container_name: Pi-Hole
        security_opt:
            - no-new-privileges=false
        volumes:
            # For persisting custom dnsmasq config files. Most will not need this, and can be safely removed/commented out
            - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
            # For persisting Pi-hole's databases and common configuration file
            - /volume1/docker/pihole/pihole:/etc/pihole:rw
     environment:
            # FTLCONF_webserver_api_password: '<password>'
            FTLCONF_webserver_port: '8181s'
            # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
            TZ: 'America/New York'
            
        cap_add:
            - SYS_NICE
        restart: on-failure:5
        network_mode: host
        image: pihole/pihole:latest
```

2. observe in the container logs that pihole has started.
3. load `https://<adress>:8181/admin`
4. observe in the logs that FTL has crashed. Admin UI does not load

## Debug Token

- URL:  https://tricorder.pi-hole.net/P24LIVmv/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

if I comment out  # FTLCONF_webserver_api_password: '<password>' it starts and the FTL ui is accessible where expected, but there's no password. Not even a randomly generated one.

I am able to set a password via `pihole setpassword` but it doesn't seem to be used - after setting it the admin UI still loads without a login challenge.

**Comment by vitaliy-sk** [comment]
Same issue on `Linux nas 3.10.108 #42962 SMP Mon May 29 14:36:16 CST 2023 x86_64 GNU/Linux synology_bromolow_3615xs`

```
2025-02-21 23:36:06.864 GMT [58M] ERROR: getrandom() failed in generate_password()
2025-02-21 23:36:06.865 GMT [58M] ERROR: Failed to generate CLI password hash!
```

It's not crashing, but UI isn't asking for password event if it was set before migration to v6

**Comment by DL6ER** [comment]
Please try again after running
```
sudo pihole checkout ftl development
```
to get the latest bug fixing attempts for this problem. The issue here is that your VMs somehow do not provide cryptographically sound randomness and we need find out why.

**Comment by GDT1978** [comment]
I have the same issue with my installation in a Synology DS415+. If I configure my docker with a blank password I was able to open the admin page.

**Comment by vitaliy-sk** [comment]
@DL6ER thanks, tried, but it's not working on Docker

```
1ad31eb40277:/# sudo !!
sudo pihole checkout ftl development
Function not supported in Docker images
```

also tried `pihole/pihole:nightly` image but no luck

**Comment by yubiuser** [comment]
If your are on docker, you need to build the image yourself.

https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#building-the-image-locally

`./build.sh -f development`

**Comment by uurf** [comment]
While I think it's within my capabilities to build locally, I'm not sure how to use a local image with my pihole container project, and deploy it reliably within my environment.

**Comment by yubiuser** [comment]
If you use the build script, it will create an image tagged `pihole:local`

You can simply change one line in your docker compose file to load this instead of the one from dockers repository.

```
services:
  pihole:
    container_name: pihole_local
    image: pihole:local

```
