### ISSUE TITLE
Version 6 does not honour X-Forwarded-Prefix header

### ISSUE THREAD

**Issue by pauruiz** [pi-hole/FTL#2298]
### Versions

- Pi-hole:  6.0.4
- AdminLTE:  6.0.1
- FTL:  6.0.2

### Platform

- OS and version:  Debian 12

- Platform:  Docker

### Expected behavior

When using Pihole docker image behind a reverse proxy like Traefik, when using PathPrefix to route to the container, and that prefix gets removed (Traefik or any reverse proxy will add and X-Forwarded-Prefix header after stripping it from the client request before sending the request to the pihole container), one should expect pihole to look for the header and honour it, appending the stripped prefix, and continue working as expected, as all links should append the X-Forwarded-Prefix to avoid breaking the links.

F.e.:
- Configuration routing the pihole containers using /pihole query string prefix
- Traefik cnofigured to remove that prefix using [stripprefix](https://doc.traefik.io/traefik/middlewares/http/stripprefix/)
- The container ignores the X-Forwarded-Prefix
- A query to http://IP/pihole/login/admin gets redirected to http://IP/login/admin, a URL Traefik cannot route to the pihole container, as it lacks the /pihole prefix

### Actual behavior / bug

Pihole v5 web server in the container honoured the X-Forwarded-Prefix header and appended it on all generated links, but latest changes in an aim to reduce the image size (impressive by the way, congratulations) have simplified the routing capabilities, ignoring the X-Forwarded-Prefix header

### Steps to reproduce

1. Download docker compose yml example from this issue.
2. This file contains Traefik router (reading docker labels on docker), whoami Traefik example on /whoami, and pihole using /pihole pathPrefix and stripping /pihole prefix)
3. Deploy using `docker compose -f traefik-pihole-issue-docker.yml  -d` 
4. Using the browser, navigate to the IP of the docker instance, path /pihole/admin (http://IP/pihole/admin)
5. Browser will redirect from /pihole/admin to /admin/login (the pihole/ prefix is lost)
6. ERROR as that path does not belong to any container and the reverse router does not know where to route it

 
 
## Debug Token

- URL:  

### Screenshots

No screenshot

### Additional context

[traefik-pihole-issue-docker.yml.tgz](https://github.com/user-attachments/files/19011487/traefik-pihole-issue-docker.yml.tgz)

On the yml file, both images are configured, comment or remove the line showing latest pihole image, and uncomment the line using 2024.07.0, and redeploy to see how v5 was correctly appending the /pihole prefix to all the links on the page

**Comment by DL6ER** [comment]
> PathPrefix

has simply not been implemented in Pi-hole as it was not requested during the extended v6 beta. So far, this header is only used to identify the requesting *client*. This has been requested during the beta. As I am not too familiar with this headers, does this mean we are using it wrong? My expectation at this moment would be that it contains only the original requesting client and nothing else. Was this wrong?

We can look at this now but I can exactly say when we get to it. If we can meanwhile "heal" my confusion around this header, this will surely be helpful. Your ready-to-be-reproduced docker-compose will prove valuable, too.

**Comment by pauruiz** [comment]
Sorry, my fault, I just mixed names in my mind...

X-Forwarded-For is the one for the client, please rephrase all the description block with:

-  X-Forwarded-Prefix header

With that change, all will make sense, the docker compose file is correct, and can be used to test both v5 and v6

I can do that for you, I don't know if you may have any policy to not amend the issues once started

**Comment by DL6ER** [comment]
There is no limiting policy regarding this, whatever makes the issue clearer for all is allowed. I did just set up your compose example and noticed two things:
1. I have to remove the `network_mode` on the `pihole` container
2. When accessing `/whoami` - as suggested - I do **not** see a `X-Forwarded-Prefix` header, full output below:
```
Hostname: ae540bcb7b9f
IP: 127.0.0.1
IP: ::1
IP: 172.28.0.2
RemoteAddr: 172.28.0.3:56876
GET /whoami HTTP/1.1
Host: 192.168.2.11:8880
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,en-US;q=0.5
Priority: u=0, i
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.2.122
X-Forwarded-Host: 192.168.2.11:8080
X-Forwarded-Port: 8080
X-Forwarded-Proto: http
X-Forwarded-Server: e5324aec57bd
X-Real-Ip: 192.168.2.122
``

Is this expected?

**Comment by pauruiz** [comment]
Yes, on the whoami, the strip prefix is set to /whoami/ <-- Please not the trailing `/`.

If you want to see the header, you can do http://IP/whoami/DL6ER

**Comment by DL6ER** [comment]
In Pi-hole before v6.0 it worked trivially without us doing anything special for it. That is because we did not need absolute paths for anything because all the individual pages were `*.php` files directly in `/admin/`. Relative paths (e.g., `vendor/...`) have always looked *inside* `/admin/` which is correct (and resolved to `/admin/vendor/...`).

The v6.0 web interface, however, does URI rewriting to get nice paths like https://pi.hole/admin/settings/dns and using relative paths is an issue now. The relative path `vendor/...` (actually still lving in `/admin`) would now resolve to `admin/settings/dns/vendor/...` if we would not be using absolute paths - not good!

However, with your prefix solution, we'd need to take this extra header into account each and every time in many places.  I tried this but we have a few hard-coded prefixes (as for the API), so this isn't really feasible without redesigning how we register dynamic endpoints in the webserver.

Hence, I have decided to - instead - add a new option `webserver.paths.prefix` defaulting to an empty string. If you set it to `/pihole`, it should immediately start working in the exact setup you have described in your `docker-compose.yml` example.

For testing, you'll need to build a custom image following the instructions here: https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#building-the-image-locally

More specifically, you'll need to run
```
./build.sh -f new/web_prefix -w new/web_prefix
```
which will build a new image that will be tagged as `pihole:local` on your local machine. Use this in your `docker-compose.yml` script and please test it carefully! If everything works as expected, this can then go into testing for the next release, probably v6.1.

Related PRs are https://github.com/pi-hole/FTL/pull/2319 and https://github.com/pi-hole/web/pull/3269.

**Comment by pauruiz** [comment]
Thanks a lot for the quick response, actions. Definitely will have a look.

On my side I am still on the migration to docker phase (real pihole used are on two ESXi VMs), and I have waved the test by creating a local domain and pausing the prefix use till fixed.

I am worried that if in a hurry to make it work, a proper solution may not be considered (even if that would take longer), and what could be the burden of maintaining this hotfix, the interesting bit of the proper one is that the same container can be used in two different locations (like mine that I have one installation for work stuff, and another for the kids) on different prefixes, working like a charm with the same image.

I have heard of a lot of people having this kind of more than one instances running (you may have better metrics on that). I have not really look at the code, and I don’t know if this could be split into two/three chunks of new sub-features, and consider this done once all are played.

Again, thanks a lot for this marvellous tool, for the quick response, and the proposed hotfix. The docker image reduction on v6 was impressive, and also to say as usually only bad thing rises, and somebody has already said. The small issues found apart from this one are to be expected in any major version migration.

Thanks, thanks a lot

**Comment by DL6ER** [comment]
Did you had a chance to try this out further? I still think making it dynamically depending on the header would kill many of our optimizations. I wouldn't consider this PR a hot fix, it is in fact a proper solution and likely the best one we can come up with, even if this limits the prefix to a single allowed one. I cleaned some code along the way and ensured this does not put up any unreasonable maintenance burden on us.

**Comment by pauruiz** [comment]
Hi Dominik,

I have managed to make it work, all fine as far as I can test (not using API). It took me a bit to build, as I was trying to execute the ./build.sh on the FTL repo, instead of the main pihole one.
Then I tried to add the settings as environment variables, but when I saw your PR change on the toml file, (and reenabling the stripprefix that I had disabled) all worked like a charm.

Once this is set, it looks a bit weird, and you may have worked more than needed. On the reverse proxy, I configured two things, one is the routing, and the other is the middleware to remove the /pihole. This is required when routing a normal app living on `/` through the reverse proxy.

But...

If in the app, we configure it to live in f.e. /pihole, the need to strip the prefix seems diluted. With the current pihole code from your PR, the stripprefix needs to be there, it may need a lot more refactor, to make the links really move to /pihole/admin, so maybe any person asking to put pihole behind a reverse proxy, should be asked for that stripprefix...

So I think it may make sense, I can see people confused on why configuring the route, and the strip middleware in the reverse proxy, and then also the webserver.paths.prefix in the pihole.toml file, but all makes sense...

That is a lot more than other applications provide.

Thank a lot for your support, that was a lightning fast coding. Sorry I had not being able to test before.

**Comment by DL6ER** [comment]
I am not sure if you are suggesting a change here or not (if you are very happy with it), let me give a bit more details on what I think is a bit in the unclear here:

1. We need to strip the prefix so the webserver can continue to serve the files without modifying the webserver itself, this actually makes the code (even much!) simpler.
  Imagine you are hosting Pi-hole on www.example.com/pihole/admin but the files are still living in `/var/www/html/admin` . There is no `pihole` in this path!
2. "floating" URLs are much more complex to handle then absolute paths. That is because we use URL rewriting for nicely looking URLs, e.g., www.example.com/pihole/admin/settings/dns but the *real* file still lives directly in `/admin/`

**Comment by dschaper** [comment]
This is what I'm testing with, and access looks good.

Compose file, running Pi-hole outside of the docker stack on the host:

```yaml
root@pht:/etc/pihole# cat traefik-pihole-issue-docker.yml 
services:
  traefik:
    image: "traefik:v3.3.3"
    container_name: "traefik"
    command:
      - "--accessLog=true"
      - "--tracing=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.dnstcp.address=:53"
      - "--entryPoints.dnsudp.address=:53/udp"
    ports:
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc-traefik:/etc/traefik:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=stripwhoami"
      - "traefik.http.middlewares.stripwhoami.stripprefix.prefixes=/whoami/"
 ```

Dynamic configuration, file provider, for the host installed Pi-hole.

```yaml
root@pht:/etc/pihole/etc-traefik# cat dynamic.yaml 
http:
  routers:
    pihole:
      entryPoints:
        - web
      rule: "PathPrefix(`/pihole`)"
      middlewares:
        - piholehttp
      service: piholehttp
  middlewares:
    piholehttp:
      stripPrefix:
        prefixes:
          - "/pihole"
  services:
    piholehttp:
      loadBalancer:
        servers:
          - url: "http://192.168.1.190:8081"
 ```

pihole.toml
```toml
# Prefix where the web interface is served
# This is useful when you are using a reverse proxy serving the web interface, e.g.,
# at http://<ip>/pihole/admin/ instead of http://<ip>/admin/. In this example, the
# prefix would be "/pihole". Note that the prefix has to be stripped away by the
# reverse proxy, e.g., for traefik:
# - traefik.http.routers.pihole.rule=PathPrefix('/pihole)
# - traefik.http.middlewares.piholehttp.stripprefix.prefixes=/pihole
# The prefix should start with a slash. If you don't use a prefix, leave this field
# empty. Setting this field to an incorrect value may result in the web interface not
# being accessible.
Don't use this setting if you are not using a reverse proxy!

Possible values are:
valid URL prefix or empty
prefix = "/pihole" ### CHANGED, default =
```

![Image](https://github.com/user-attachments/assets/5c79a9f0-2337-4b78-8de4-9491f5abca67)

![Image](https://github.com/user-attachments/assets/9e45f55c-8d83-46bd-a999-5a72edb06f7c)

**Comment by darkexplosiveqwx** [comment]
This currently causes issues with padd( or anything using `domain.api.ftl`)
My prefix is `/pihole`, nginx is running with https on port `443`, FTL is binding to `172.0.0.1:8080`. 
```bash
 $ dig +short chaos txt domain.api.ftl @localhost
"http://pi.hole:8080/pihole/api/"
```
The output should be either `"http://pi.hole:8080/api/"` or `"https://pi.hole:443/pihole/api/"`.
Currently FTL has no option to know what path and http[s] the reverse proxy is using.

**Comment by pauruiz** [comment]
I have found another issue/not fully working, dashboard worked fine, but when going to local DNS, list did not update, a network debug on the browser showed that those calls to the API were not properly generated, while other entries were having the expected path, on the same DNS query, could be seen.

OK (instance at /piholelan):
- http://swarm.iosnow.net/piholelan/api/dns/blocking
- http://swarm.iosnow.net/piholelan/api/info/messages/count
- http://swarm.iosnow.net/piholelan/api/info/ftl
- http://swarm.iosnow.net/piholelan/api/info/system

Not working (missing prefix path):
- http://swarm.iosnow.net/api/config/dns/cnameRecords?_=1743967062282
- http://swarm.iosnow.net/api/config/dns/hosts?_=1743967062281

I have made a quick recap of all the menu entries, and this one was the only one failing (I am to still to click on all the buttons, to confirm that all the action URLs are correct)

@darkexplosiveqwx - I don't think the host/port of the TXT record may be related to this, I agree with you, that currently pihole cannot know which host/port it is listening to, but that should not be related to this, and in any case, due to this, if we were to implement it in full, it could only get worse, if fully honouring the X-Forwarded-For HTTP header, pihole effectively should never know nothing about where it is deployed, and will work out the paths from the original query from the client. The TXT entry with the current published entry, should be configured in other place. This directive is good f.e. in my case, I have a `/piholelan` and a `/piholedmz`. If you are running a single pihole instance, you may not need this directive at all. If running the pihole behind a reverse proxy, you could redirect all /admin and /api entries directly to the pihole container.
Once this is said, your suggestion of not using this prefix in the TXT creation, may be a good idea..., but that may and will vary with how people will embed pihole in their networks, so any default/non-configurable TXT entry, will never satisfy 100% of the use cases...

**Comment by calliecameron** [comment]
I'm trying to set up the same thing. However, when reverse proxied with the `/pihole` prefix, the CSRF token on the admin page is not set (`<meta name="csrf-token" content="">`), all the API calls fail with 401 unauthenticated, and the page goes into a refresh loop. The cookie appears to be getting set - it's just the CSRF token that's missing.

When reverse proxying without a prefix, the CSRF token is set and everything works.

I.e., the admin page works here:

```yaml
services:
  pihole:
    image: "pihole/pihole:2025.06.2"
    environment:
      FTLCONF_WEBSERVER_API_PASSWORD: "foobar"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=control_panel"
      - "traefik.http.routers.pihole.rule=PathPrefix(`/admin`) || PathPrefix(`/api`)"

networks:
  "traefik":
    external: true
```

And doesn't work here:

```yaml
services:
  pihole:
    image: "pihole/pihole:2025.06.2"
    environment:
      FTLCONF_WEBSERVER_API_PASSWORD: "foobar"
      FTLCONF_WEBSERVER_PATHS_PREFIX: "/pihole"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=control_panel"
      - "traefik.http.routers.pihole.rule=PathPrefix(`/pihole`)"
      - "traefik.http.middlewares.pihole-path.stripprefix.prefixes=/pihole"
      - "traefik.http.routers.pihole.middlewares=pihole-path"

networks:
  "traefik":
    external: true
```

**Comment by calliecameron** [comment]
This is not stale, please reopen.

**Comment by calliecameron** [comment]
Not stale.

**Comment by hawksj** [comment]
Following as I am also having trouble with this. Following the documentation within /etc/pihole/pihole.toml under webserver.paths.prefix, I added the suggested stripPrefix middleware to the Pi Hole service with Traefik but like calliecameron, I get a refresh loop. Unusual that following the docs as recommended causes unintended behaviour, I guess this feature isn't ready. Will work around with a subdomain. Here are my configs where relevant.
_dynamic Traefik file:_
```yml

http:
  routers:
    pihole-router:
      rule: "Host(`admin.myname.co.uk`) && PathPrefix(`/pihole`)"
      entryPoints:
        - internal
      service: pihole-service
      middlewares: "pihole-stripprefix"
      tls:
        certResolver: le
  services:
    pihole-service:
      loadBalancer:
        servers:
          - url: "https://pihole:443"
  middlewares:
    pihole-stripprefix:
      stripPrefix:
        prefixes:
          - "/pihole"
```
_docker-compose.yaml:_
```yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.08.0
    hostname: pihole-dns
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      #- "81:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/London'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      WEBPASSWORD_FILE: pihole_webpasswd
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_piholePTR: "HOSTNAMEFQDN"
      FTLCONF_dns_domain: "myname.co.uk"
      FTLCONF_webserver_paths_prefix: "/pihole/"
      FTLCONF_webserver_domain: "myname.co.uk"
```
_Referenced documentation from pihole.toml:_

    # Sub-directory of the root containing the web interface
    #
    # Possible values are:
    #     <valid subpath>, both slashes are needed!
    webhome = "/admin/"

    # Prefix where the web interface is served
    # This is useful when you are using a reverse proxy serving the web interface, e.g.,
    # at http://<ip>/pihole/admin/ instead of http://<ip>/admin/. In this example, the
    # prefix would be "/pihole". Note that the prefix has to be stripped away by the
    # reverse proxy, e.g., for traefik:
    # - traefik.http.routers.pihole.rule=PathPrefix(`/pihole`)
    # - traefik.http.middlewares.piholehttp.stripprefix.prefixes=/pihole
    # The prefix should start with a slash. If you don't use a prefix, leave this field
    # empty. Setting this field to an incorrect value may result in the web interface not
    # being accessible.
    # Don't use this setting if you are not using a reverse proxy!
    #
    # Possible values are:
    #     valid URL prefix or empty
    prefix = "/pihole/" ### CHANGED (env), default = ""
