### ISSUE TITLE
Environment Variable Parsing

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/FTL#2339]
Currently, to pass an array item into an environment variable it needs to look something like:

```yaml
FTLCONF_dns_hosts: '127.0.0.1 google.com;127.0.0.2 facebook.com'
```

![Image](https://github.com/user-attachments/assets/03a01d34-cad3-42aa-bbc1-6280b50bc40f)

```toml
[dns]
  # Array of custom DNS records
  # Example: hosts = [ "127.0.0.1 mylocal", "192.168.0.1 therouter" ]
  #
  # Possible values are:
  #     Array of custom DNS records each one in HOSTS form: "IP HOSTNAME"
  hosts = [
    "127.0.0.1 google.com",
    "127.0.0.2 facebook.com"
  ] ### CHANGED (env), default = []
```

This is fine for a couple of values, but gets quite unreadable when you want to add in more.

Another way of passing these in would be:

```yaml
FTLCONF_dns_hosts: |
    127.0.0.1 google.com
    127.0.0.2 facebook.com
    127.0.0.3 somethingelse.com
    127.0.0.4 you-get-the-point-im-trying-to-make.org
```

While this looks normal here:

![Image](https://github.com/user-attachments/assets/172f4f24-be4b-40ef-bbd1-ce7c57d4dcd3)

It looks odd in the config file:

```toml
[dns]
  # Array of custom DNS records
  # Example: hosts = [ "127.0.0.1 mylocal", "192.168.0.1 therouter" ]
  #
  # Possible values are:
  #     Array of custom DNS records each one in HOSTS form: "IP HOSTNAME"
  hosts = [
    "127.0.0.1 google.com\n127.0.0.2 facebook.com\n127.0.0.3 somethingelse.com\n127.0.0.4 you-get-the-point-im-trying-to-make.org\n"
  ] ### CHANGED (env), default = []
```

Weird still on the local DNS settings page:

![Image](https://github.com/user-attachments/assets/d6de3e90-d15f-49ec-a22b-5909a4848680)

However the actual resolution of these hosts works despite that:

![Image](https://github.com/user-attachments/assets/06ab0232-0337-47ad-8803-8d31530efea2)

Is there something we can do to pretty this up a bit?
