### ISSUE TITLE
REST API /history endpoint returning negative values for some fields

### ISSUE THREAD

**Issue by avojak** [pi-hole/FTL#2343]
### Versions

- Pi-hole:  6.0.4 (core version)
- AdminLTE:  6.0.1 (web version)
- FTL:  6.0.2

### Platform

- OS and version:  macOS 15.3.1

- Platform:  Docker

### Expected behavior

The `total`, `cached`, `blocked` and `forwarded` fields in the response for the `/history` REST API endpoint should always return non-negative values.

### Actual behavior / bug

Some entries in the response contain negative values. For example:

```json
    {
      "timestamp": 1741214100,
      "total": 0,
      "cached": -2,
      "blocked": 0,
      "forwarded": -2
    }
```

### Steps to reproduce

1. Invoke the API endpoint and inspect the response

```
curl -qs "localhost:8080/api/history" -H 'X-FTL-SID: REDACTED'
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/XRC68otv/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

The Pi-hole instance was running locally as a container on my laptop with several other containers simulating web traffic.

Nothing unusual was happening with my laptop at the timestamp shown in the API response above, it was just sitting on my desk untouched.

For reference, this is the Docker Compose file that I was using:

```yaml
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - "TZ=America/Denver"
      - "FTLCONF_webserver_api_password=password123"
      - "FTLCONF_dns_upstreams=1.1.1.1;1.0.0.1"
      - "FTLCONF_dns_listeningMode=local"
      - "FTLCONF_dns_domainNeeded=true"
      - "FTLCONF_dns_dnssec=false"
    networks:
      testbr:
        ipv4_address: 10.5.0.5

  traffic-generator:
    build:
      context: ./traffic-generator
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      testbr:
    dns:
      - 10.5.0.5
    scale: 5

networks:
  testbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
```
