### ISSUE TITLE
Admin pages delays for several seconds, even on clean install

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/FTL#2363]
Use the docker container to setup a clean, empty install of latest development snapshot (using :nightly), issue is also reproducable with 6.0.4 (:latest). Do not change any settings, do not use pihole for your DNS requests, simply download and set it up. Click around on the admin web quickly. You will see some strange lags. I can reproduce it by switching between Dashboard and Query Log quickly for several times.

I cannot see anything unusual on the locks debug output. Butfor me it looks like locks are not released somewhere on concurrent webserver requests that query the database.

This is the docker-compose.yml I use:

```
  pihole:
    container_name: pihole
    image: ghcr.io/pi-hole/pihole:nightly
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '2'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/data/docker/pihole/etc:/etc/pihole'
      - '/opt/data/docker/pihole/dnsmasq.d:/etc/dnsmasq.d'
      - '/opt/data/docker/pihole/logs:/var/log/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped
```
