### ISSUE TITLE
DHCP renewal fails if a DHCP relay is used

### ISSUE THREAD

**Issue by ZakKemble** [pi-hole/FTL#2397]
### Versions
- Core version is v6.0.5 (Latest: v6.0.5)
- Web version is v6.0.2 (Latest: v6.0.2)
- FTL version is v6.0.4 (Latest: v6.0.4)

### Platform
- OS and version:  Debian 11.11
- Platform:  Docker

### Expected behavior

DHCP renewal is successful - as in the client sends a unicast renewal request to the DHCP server (specified by the `server-identifier` option) and the server responds

### Actual behavior / bug

DHCP renewal fails and a rebind (broadcast) is performed instead because the `server-identifier` is set to that of the docker container IP (usually a 172.16.0.0/12 address) instead of the docker host IP or DHCP relay IP.

Someone else has had the same problem here: https://www.reddit.com/r/pihole/comments/jiqdna/pihole_on_docker_dhcp_offer_contains_internal/

It looks like this could be an easy fix by removing the `OT_INTERNAL` flag which will allow overriding this option with `dhcp-option=option:server-identifier:<host IP>` (similar to how `dns-server` and `ntp-server` options need to be overridden)

https://github.com/pi-hole/FTL/blob/b7eb53bf32ab76546db87c6db6d7085526788d67/src/dnsmasq/dhcp-common.c#L684

### Steps to reproduce

Docker containers setup as described here with bridge networking and DHCP relay https://docs.pi-hole.net/docker/DHCP/

```yml
services:

  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 443:443/tcp
      - 123:123/udp
    environment:
      - TZ=Europe/London
      - FTLCONF_dns_interface=eth0
      - FTLCONF_dns_listeningMode=ALL
      - FTLCONF_dns_domain=localnet
      - FTLCONF_dns_upstreams=1.1.1.1
      - FTLCONF_dhcp_active=true
      - FTLCONF_dhcp_start=10.0.0.10
      - FTLCONF_dhcp_end=10.0.0.99
      - FTLCONF_dhcp_router=10.0.0.1
      - FTLCONF_dhcp_netmask=255.255.255.0
      - FTLCONF_dhcp_leasetime=24h
      - FTLCONF_misc_dnsmasq_lines=dhcp-option=option:dns-server,10.0.0.2;dhcp-option=option:ntp-server,10.0.0.2
    volumes:
      - ./pihole/data:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      dhcp-relay-net:
        ipv4_address: 172.31.0.10

  dhcphelper:
    container_name: dhcphelper
    build: ./dhcphelper
    restart: always
    network_mode: host
    command: -s 172.31.0.10
    stop_signal: SIGKILL
    cap_add:
      - NET_ADMIN

networks:
  dhcp-relay-net:
    ipam:
      config:
        - subnet: 172.31.0.0/16

```

Dockerfile for dhcphelper:

```
FROM alpine:latest
RUN apk --no-cache add dhcp-helper && rm -rf /var/cache/apk/*
ENTRYPOINT ["dhcp-helper", "-n"]
```

### Screenshots

```shell
$nmap --script broadcast-dhcp-discover -e enp1s0
Starting Nmap 7.80 ( https://nmap.org ) at 2025-03-29 21:30 GMT
Pre-scan script results:
| broadcast-dhcp-discover:
|   Response 1 of 1:
|     IP Offered: 10.0.0.39
|     DHCP Message Type: DHCPOFFER
|     Server Identifier: 172.31.0.10     <========= !
|     IP Address Lease Time: 2m00s
|     Renewal Time Value: 1m00s
|     Rebinding Time Value: 1m45s
|     Subnet Mask: 255.255.255.0
|     Broadcast Address: 10.0.0.255
|     Domain Name: localnet
|     NTP Servers: 10.0.0.2
|     Domain Name Server: 10.0.0.2, 10.0.0.2, 10.0.0.2
|_    Router: 10.0.0.1
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 3.85 seconds

```
