### ISSUE TITLE
Diagnosis shows errors about invalid hostnames incorrectly

### ISSUE THREAD

**Issue by DPattee** [pi-hole/FTL#2452]
<img width="1085" alt="Image" src="https://github.com/user-attachments/assets/fb87c949-5bc3-4abf-8721-c3dd4cf5698e" />

### Versions
Docker Tag [2025.04.0](https://github.com/pi-hole/docker-pi-hole/releases/2025.04.0)
Core [v6.0.6](https://github.com/pi-hole/pi-hole/releases/v6.0.6)
FTL [v6.1](https://github.com/pi-hole/FTL/releases/v6.1)
Web interface [v6.1](https://github.com/pi-hole/web/releases/v6.1)

### Platform
Synology docker

### Expected behavior

No 'hostname' errors in the log with weird names

### Actual behavior / bug

Error number tag in the Tools:Pi-hole diagnosis entry, and the error in the log that appears occasionally is nonsensical. 

"Hostname of client <ip> => "PX!dU" contains (at least) one invalid character (hex 50) at position 0."
The hostname and  invalid character position changes occasionally. 

The clients it claims about are all real computers by IP address and they all have normal names entered through normal means (raspberry pi name entered through rasp-config, Mac entered through the normal Sharing panel)

### Steps to reproduce

1. Use pihole.
2. open the dashboard.
3. see that there is an error on the pi-hole diagnosis page.

## Debug Token

- URL:  https://tricorder.pi-hole.net/ushrQ2RW/

### Screenshots

screenshot attached of another instance of the bug that matches the description of the error message provided above.

### Additional context

```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    # uncomment ports section if switching to docker 'bridge' instead of 'host' networking
    # ports:
      # DNS Ports
      # - "53:53/tcp"
      # - "53:53/udp"
      # Default HTTP Port
      # - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      TZ: 'America/Los_Angeles'
      FTLCONF_webserver_port: '7080'
      FTLCONF_webserver_api_password: '1'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/volume1/docker/pihole-v6/pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      # - '/volume1/docker/pihole-v6/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
```
