### ISSUE TITLE
Local addresses defined in dnsmasq config return NXDOMAIN

### ISSUE THREAD

**Issue by DragonQ** [pi-hole/FTL#2497]
### Versions

- Docker Tag: 2025.06.0
- Core: v6.1.2
- FTL: v6.2.2
- Web interface: v6.2.1]

### Platform
- OS and version:  Docker
- Platform: Docker

### Expected behavior

Local addresses defined in dnsmasq config should return correct IPs when `misc.etc_dnsmasq_d` is enabled, e.g.:

```
server=/lan/192.168.1.254
server=/1.168.192.in-addr.arpa/192.168.1.254
server=/iot.lan/192.168.2.254
server=/2.168.192.in-addr.arpa/192.168.2.254
server=/not.lan/192.168.3.254
server=/3.168.192.in-addr.arpa/192.168.3.254
```

### Actual behavior / bug

All local addresses return `NXDOMAIN`.

### Steps to reproduce

`nslookup device.lan`

## Debug Token

- URL: https://tricorder.pi-hole.net/JkPBVQ1R

### Additional context

Downgrading to image 2025.4.0 (FTL 6.1) fixes the issue.

```
services:
  pihole:
    container_name: pihole
    image: 'pihole/pihole:latest'
    restart: unless-stopped
    networks:
      pihole-net:
        ipv4_address: ${PIHOLE_IP}
    volumes:
      - ${PIHOLE_ROOT_PATH}/etc/:/etc/pihole/
      - ${PIHOLE_ROOT_PATH}/log/:/var/log/
      - ${PIHOLE_ROOT_PATH}/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - '${HOST_IP}:53:53/tcp'
      - '${HOST_IP}:53:53/udp'
      - '${HOST_IP}:${PIHOLE_GUI_PORT}:80/tcp'
    environment:
      - TZ='Europe/London'
      - WEBPASSWORD=${PIHOLE_GUI_PASSWORD}
      - DNS1=${PIHOLE_UPSTREAM_DNS}
      - DNS2=no
      - MAXDBDAYS=60
    dns:
      - 127.0.0.1
      - 208.67.222.222
  unbound:
    container_name: unbound
    image: 'klutchell/unbound:latest'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # Needed to fix so-rcvbuf & so-sndbuf errors
    networks:
      pihole-net:
        ipv4_address: ${UNBOUND_IP}
    volumes:
      - ${UNBOUND_ROOT_PATH}/etc/unbound.conf:/etc/unbound/unbound.conf
      - ${UNBOUND_ROOT_PATH}/log/unbound.log:/var/unbound/unbound.log:rw
```
